site_name: {{ cookiecutter.project_name }}
site_url: https://{{ cookiecutter.github_name }}.github.io/{{ cookiecutter.project_name }}
repo_url: https://github.com/{{ cookiecutter.github_name }}/{{ cookiecutter.project_name }}
repo_name: {{ cookiecutter.github_name }}/{{ cookiecutter.project_name }}
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
  - meta
plugins:
  - search:
      lang: en
  - mkdocstrings:
  - include-markdown
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: https://github.com/{{ cookiecutter.github_name }}/{{ cookiecutter.project_name }}
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: https://github.com/{{ cookiecutter.github_name }}/{{ cookiecutter.project_name }}
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.github_name }}/{{ cookiecutter.project_name }}
      name: Github
    - icon: material/email
      link: "mailto:{{ cookiecutter.email }}"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
# google_analytics:
#   - UA-xxx
#   - auto